<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/loan/loan-status/change-installment.js'));

?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.pullLoanListLink = '<?= $this->url("loanRequest", ["action" => "pullLoanList"]) ?>';
</script>

<div class="page-bar">
    <?= ''//$this->navigation('Zend\Navigation\loanApply')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row margin-top-20" ng-app="hris" ng-controller="loanController">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Change Installment
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <form method="POST" action="<?= $this->url('loanApply', ['action' => 'changeInstallment', 'id' => $id, 'eid' => $eid]) ?>">
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                        <label>Employee</label>
                            <select name="employee" disabed="disabled" readonly="readonly">
                                <option value="<?php echo key($employee); ?>"><?php echo $employee[key($employee)]; ?></option>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="unpaidTotal">Total Unpaid Amount</label>
                            <div class="input-group">
                                <input type="number" class="form-control" step="0.01" readonly="readonly" id="unpaidTotal" value="<?=$unpaidAmount?>" name="unpaidTotal">
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="installment">Installment</label>
                            <div class="input-group">
                                <input type="number" class="form-control" id="installment" step="0.01" readonly name="installment">
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="months">Months</label>
                            <div class="input-group">
                                <input type="number" class="form-control" step="0.01" id="months" name="months">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                        <label for="unpaidTotal">Remarks</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="remarks" name="remarks">
                            </div>
                        </div>
                    </div>
                    
                </div>

                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                        <button id="submit">Submit</button>
                    </div>
                    </div>
                </div>
                </form>
            </div>

        </div>
    </div>
</div>
